version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/market-research
      - NODE_ENV=production
    volumes:
      - ./packages/api/.env:/app/.env

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    volumes:
      - ./packages/ui/.env:/app/.env

volumes:
  mongo-data:
