name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/api/**'
      - 'packages/client-common/**'
      - 'packages/tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/api/**'
      - 'packages/client-common/**'
      - 'packages/tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build client-common package
      run: |
        cd packages/client-common
        npm run build
    
    - name: Start API server in background
      run: |
        cd packages/api
        npm run dev &
        sleep 10
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/todo-test
        JWT_SECRET: test-secret
        PORT: 3001
    
    - name: Run tests
      run: |
        cd packages/tests
        npm test
      env:
        NODE_ENV: test
        API_BASE_URL: http://localhost:3001/api
        
    - name: Display test results
      if: always()
      run: echo "Tests completed - check above for results"